// Lexical Grammar. 
%lex

%%
\s+                  /* skip whitespace */
\/\*.*?\*\/          /* skip comment */
\d+                  return 'NUMBER'
\"[^\"].*\"          return 'STRING'
(true|false)         return 'BOOLEAN'
[\w+\-+*=<>/]+       return 'SYMBOL'
-
/lex

%%
EXP 
     : ATOM
     | LIST
     ;

ATOM 
     : COMMENT
     | NUMBER  { $$ = Number($1) }
     | STRING 
     | SYMBOL
     | BOOLEAN {{ $$ = $1 ==='true' ? true : false}}
     ;

LIST 
     : '(' LIST_ENTRIES ')' { $$ =  $2 }
     ;

LIST_ENTRIES
     : LIST_ENTRIES EXP { $1.push($2); $$ = $1}
     | /* empty */ { $$ = [] }
     ;